language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: antirek@yandex.ru
  api_key:
    secure: Er25ew35AFXlROk2cyQBeNjQNxu0i3q/1NXdg4o5g45Uvo6Y6xrSqaCwcAD3SViB0A/5MhkLIWh2rM8GsTs1udS31fb9jWIKw0OYiBgkJMyGS/kKf9YqEtjpWpFhZLqyIfHjTsW62y8fw5OluKszCBVBpHmTvtXXhqVsE2nMx2hDd2zIXDJsQctDP1Wkk1xgUP0CGMImeH0rA1q85LPaNcItrw4ecgedIPNkPxBnh7kTiBmDE8MYmpxZsPXDsOdWkIuTzzOHBeyjXwloWkToRu71G59L1VgCpLP0aqmbz89y+Z2rJiKjFPiN5cuX7i2Wi5xVxTS0hs3MMEvhW5s51mlkguUv40AxfuR5pk81tcNemB6cpzOoL9rbzdzcBQeE5PRml0qYH/RzbU+OBu69Je+Zz0ltrFnFhR0LRaa4DHFKiMysCFJphso/FKrdzenAI46WCiVsl2LGsgCQstUEF5/1H/379Wcnz7xsgyTQN1onr7aDrGemKsi6VFlQKcGengMUmeR/qQ4ZByRL8sCHL//0okPCvM16zLkfW4Be82nRLyu6lqMvRTp2RMbPc0+PUFV4/CtaA9XtrrB2hNlWcfLGCfZd0IOZOGzKckVm86ZABqaKOZgSj/v+YZZLxOPKBwoHo/iCiw8ZBlSAiCKsSat9g3WroFwo+1rnGobpGNc=
  on:
    repo: antirek/goip-sms
